name: bilgi_yarismasi
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_screenutil: ^5.6.0
  step_progress_indicator: ^1.0.2
  fluttertoast: ^8.1.1
  firebase_auth: ^4.2.0
  firebase_core: ^2.4.0
  cloud_firestore: ^4.2.0
  google_sign_in: '^4.5.1'

dev_dependencies:
  flutter_test:
    sdk: flutter

  #flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/

  #example:
  fonts:
    - family: Prompt
      fonts:
        - asset: assets/fonts/Prompt-Regular.ttf
